---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: restores.mydumper.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: Ready
    type: string
  group: mydumper.com
  names:
    kind: Restore
    plural: restores
    shortNames:
    - rs
  scope: Namespaced
  validation:
    openAPIV3Schema: {}
  version: v1alpha1
